version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/app/src
    container_name: genially-backend
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm run dev
