version: '3.7'

networks:
  code_test:

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/app/src
    networks:
      - "code_test"
    container_name: genially-backend
    expose:
      - '3000'
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    command: npm run dev
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    networks:
      - "code_test"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root